SELECT SUBSTR(T.CARD_NUM,2) as CARD_NUM, MIN(TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYY.MM.DD')) as INS, count (*) as kol_t
, MAX(SUBSTR(REPLACE(C.SOCIAL_CARD,' ',''),1,19)) as SOCIAL_CARD, MAX(TO_CHAR(TRUNC(C.DATE_OF_TRAVEL_DOC_KIND_LAST,'DD'), 'YYYY.MM.DD')) as LAST_ACTIVE
 FROM CPTT.T_DATA T
      INNER JOIN CPTT.CARD C  ON T.ID_CARD=C.ID
WHERE  T.DATE_OF > TO_DATE('01.02.2015 00:00:00','DD.MM.YYYY HH24:MI:SS')
--and T.kind in (7,12)
and  T.CARD_SERIES  in (80) 
and T.DATE_OF > TO_DATE('01.01.2015 00:00:00','DD.MM.YYYY HH24:MI:SS')
--and SUBSTR(REPLACE(C.SOCIAL_CARD,' ',''),1,19) = '9643500250022902351'
GROUP BY T.CARD_NUM
ORDER BY MIN(TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYY.MM.DD'))
--select * from CPTT.CARD C where C.series=80
