SELECT 
 T.TAPE_RN, TE.CODE,  MIN(T.SHIFT_begin), MAX(T.SHIFT_END), count(*) as KOL
  --,T.FILE_RN, T.ID_FILE_LOAD, T.SHIFT_begin, T.SHIFT_END, R.CODE,  T.ID_TERM,
--TE.*, 'ROUTE',R.*,  T.*, 'FILE',F.*
 FROM CPTT.T_DATA T
    INNER JOIN CPTT.DIVISION D ON T.ID_DIVISION=D.ID
    INNER JOIN CPTT.OPERATOR O ON D.ID_OPERATOR=O.ID  and O.ROLE=1
    INNER JOIN CPTT.ROUTE R ON T.id_route=R.ID AND T.id_division = R.id_division
    INNER JOIN CPTT.REF_JPERSON J ON O.ID_JPERSON=J.ID
    INNER JOIN CPTT.REF_BANK B ON J.ID_BANK_ACCOUNT=B.ID
    INNER JOIN cptt.TERM TE ON T.ID_TERM=TE.ID
    INNER JOIN CPTT.FILE_LOAD F ON T.id_file_load = F.ID
 WHERE
   TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'DDMMYYYY') = '01022016'
     AND T.CARD_SERIES  in (83) 
     AND O.CODE = '0016'
     AND   T.KIND=17 
--AND TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'DDMMYYYY') = '01022016'
--AND TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'DDMMYYYY') = '29022016'
--AND T.DATE_TO=TO_DATE('29.02.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
GROUP BY T.TAPE_RN, TE.CODE
ORDER BY T.TAPE_RN, TE.CODE


