--r4
SELECT SUBSTR(T.CARD_NUM,2) as NUM, O.CODE as CARRIER, count (*) as TRIP_COUNT
--,T.AMOUNT AS TARIF
--,0 as TARIF
,R.CODE as MARSH
--, MAX(decode(R.ID_CODE_MSG,200001000,0,20)) as TARIF
--, decode(R.ID_CODE_MSG,200001000,1,0) as VID
--, T.*
 FROM CPTT.T_DATA T
    INNER JOIN CPTT.DIVISION D ON T.ID_DIVISION=D.ID
    INNER JOIN CPTT.OPERATOR O ON D.ID_OPERATOR=O.ID  and O.ROLE=1
    INNER JOIN CPTT.ROUTE R ON T.id_route=R.ID AND T.id_division = R.id_division
 WHERE 
    nvl(T.NEW_CARD_SERIES, T.CARD_SERIES)  in (82,83)  
     --nvl(T.NEW_CARD_SERIES, T.CARD_SERIES)  in (82)  --prigorod
     and O.CODE ='0021'
AND   T.KIND=17 
AND TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'DDMMYYYY') = '01072017'
AND T.INS_DATE < TO_DATE('02.08.2017  9:27:55','DD.MM.YYYY HH24:MI:SS') 
AND R.ID_CODE_MSG=200001000
--exclude >30
and T.ID not in (0)
--exclude STOLLEN CARD
AND t.card_num NOT IN (
 '0003024684' --test card
) 
--and  decode(R.ID_CODE_MSG,200001000,1,0) = 0 -- 0-ai?ianeea, 1-i?eai?ia
GROUP BY SUBSTR(T.CARD_NUM,2), O.CODE,  R.CODE
ORDER BY O.CODE, R.CODE, SUBSTR(T.CARD_NUM,2) 
