SELECT
T.CARD_NUM as "Карта", T.DATE_OF as "Дата_время"

, O.NAME as "Перевозчик"
--, R.NAME as "Маршрут"
--, T.DATE_TO 
,TT.CODE  as "Терминал_(т/с)"
,decode(T.KIND, 17, 'Поездка') as "Операция"
,T.DATE_TO
--, TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'YYYYMMDD')  as "Месяц"
--TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYYMMDD') as D,
--O.NAME, R.CODE, MAX(R.NAME) as MNAME,   count(*) as kol --, T.*
--'964310380'||T.CARD_NUM as NUM, O.CODE, count (*) as kol_t
 FROM CPTT.T_DATA T
    INNER JOIN CPTT.DIVISION D ON T.ID_DIVISION=D.ID
    INNER JOIN CPTT.OPERATOR O ON D.ID_OPERATOR=O.ID  and O.ROLE=2
    --INNER JOIN CPTT.ROUTE R ON T.id_route=R.ID AND T.id_division = R.id_division
    INNER JOIN CPTT.TERM TT ON T.ID_TERM=TT.ID
    
 WHERE  
 --TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'DDMMYYYY') = '01032016'
 T.DATE_OF BETWEEN TO_DATE('01.05.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
                      AND TO_DATE('01.09.2016 00:00:01','DD.MM.YYYY HH24:MI:SS')    
-- AND T.KIND=17
 AND T.KIND in (7,12)
 --AND T.CARD_SERIES = 83
-- AND O.CODE='0022'
AND T.CARD_NUM IN
 ('0003003543',
'0003006702',
'0003011380',
'0003013717',
'0003021298',
'0003026918'
)
ORDER BY T.CARD_NUM, T.DATE_OF
 --GROUP BY  TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYYMMDD'),O.NAME,R.CODE
 --ORDER BY TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYYMMDD'),O.NAME,R.CODE
     

