SELECT 
TO_CHAR(TRUNC(T.DATE_OF,'MI'),'HH24') as HOUR_,
O.NAME,
R.NAME,
count(*) as kol --, T.*
FROM CPTT.T_DATA T
    INNER JOIN CPTT.DIVISION D ON T.ID_DIVISION=D.ID
    INNER JOIN CPTT.OPERATOR O ON D.ID_OPERATOR=O.ID  and O.ROLE=1
    INNER JOIN CPTT.ROUTE R ON T.id_route=R.ID AND T.id_division = R.id_division
 WHERE  
 --TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'DDMMYYYY') = '01032016'
 T.DATE_OF BETWEEN TO_DATE('01.04.2016 00:00:00','DD.MM.YYYY HH24:MI:SS')
                      AND TO_DATE('01.05.2016 23:59:59','DD.MM.YYYY HH24:MI:SS')    
 AND T.KIND=16
 AND  nvl(T.NEW_CARD_SERIES, T.CARD_SERIES)  in (30,33)
-- AND O.CODE='0022'
--and  R.CODE = '5'  and R.NAME = 'π 5  "¿¬“Œ—“¿Õ÷»ﬂ-ﬁ√Œ¬Œ—“Œ◊Õ€…'
 GROUP BY  TO_CHAR(TRUNC(T.DATE_OF,'MI'),'HH24') ,O.NAME,R.NAME
 ORDER BY  TO_CHAR(TRUNC(T.DATE_OF,'MI'),'HH24'),O.NAME,R.NAME
     
