--количество терминалов на линии по  коду предприятия
SELECT Data, count(*) as kol from (
  SELECT TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYYMMDD') as Data
  --, T.ID_TERM as TERM
  ,TT.CODE
  --, T.*
 FROM CPTT.T_DATA T
 INNER JOIN CPTT.CARD C ON T.ID_CARD=C.ID
 INNER JOIN CPTT.TERM TT ON T.ID_TERM=TT.ID
 INNER JOIN CPTT.DIVISION D ON TT.ID_DIVISION=D.ID
 INNER JOIN CPTT.OPERATOR O ON D.ID_OPERATOR=O.ID  and O.ROLE=1
 WHERE
  O.CODE = '0030' 
AND  (T.KIND=16 OR T.KIND=17 OR T.KIND=18 OR T.KIND=19) --списание
and T.DATE_OF >=TO_DATE('20151201', 'YYYYMMDD')
 --AND TO_CHAR(TRUNC(T.DATE_OF,'MM'), 'DDMMYYYY') = '01092015' --дата
 GROUP BY TO_CHAR(TRUNC(T.DATE_OF,'DD'), 'YYYYMMDD'), TT.CODE --T.ID_TERM
) R
GROUP BY Data
ORDER BY Data

